#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import sys

from PySide.QtGui import QMainWindow, QApplication, QSizePolicy, QWidget, QFont, QHBoxLayout, QVBoxLayout, QSpacerItem, QTimeEdit, QAbstractSpinBox, QPushButton, QPixmap, QIcon, QMenuBar, QStatusBar
from PySide.QtCore import QRect, Qt, QSize

class MainWindow(QMainWindow):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)
        self.setObjectName("MainWindow")
        self.setEnabled(True)
        self.setFixedSize(240, 150)
        self.setWindowTitle(QApplication.translate("MainWindow", "pycopersicum", None, QApplication.UnicodeUTF8))
        
        self.centralwidget = QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QRect(10, 10, 221, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        
        self.timeEdit = QTimeEdit(self.verticalLayoutWidget)
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.timeEdit.setFont(font)
        self.timeEdit.setAutoFillBackground(False)
        self.timeEdit.setAlignment(Qt.AlignCenter)
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.timeEdit.setAccelerated(False)
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit.setDisplayFormat(QApplication.translate("MainWindow", "HH:mm:ss", None, QApplication.UnicodeUTF8))
        self.timeEdit.setSpecialValueText("--:--:--")
        self.horizontalLayout_2.addWidget(self.timeEdit)
        
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        
        self.new_session_button = QPushButton(self.verticalLayoutWidget)
        self.new_session_button.setEnabled(True)
        self.new_session_button.setMaximumSize(QSize(32, 32))
        self.new_session_button.setBaseSize(QSize(0, 0))
        self.new_session_button.setText("")
        icon = QIcon()
        icon.addPixmap(QPixmap(sys.path[0] + "/icons/appointment-new.png"), QIcon.Normal, QIcon.Off)
        self.new_session_button.setIcon(icon)
        self.new_session_button.setIconSize(QSize(32, 32))
        self.new_session_button.setObjectName("new_session_button")
        self.horizontalLayout.addWidget(self.new_session_button)
        self.new_session_button.clicked.connect(self.new_session)
        
        self.pushButton_3 = QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setMaximumSize(QSize(32, 32))
        self.pushButton_3.setText("")
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(sys.path[0] + "/icons/media-playback-start.png"), QIcon.Normal, QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QSize(32, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton = QPushButton(self.verticalLayoutWidget)
        self.pushButton.setEnabled(False)
        self.pushButton.setMaximumSize(QSize(32, 32))
        self.pushButton.setText("")
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(sys.path[0] + "/icons/media-playback-stop.png"), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_4 = QPushButton(self.verticalLayoutWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMaximumSize(QSize(32, 32))
        self.pushButton_4.setInputMethodHints(Qt.ImhNone)
        self.pushButton_4.setText("")
        self.pushButton_4.setEnabled(False)
        icon3 = QIcon()
        icon3.addPixmap(QPixmap(sys.path[0] + "/icons/media-playback-pause.png"), QIcon.Normal, QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QSize(32, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(self)
        self.menubar.setGeometry(QRect(0, 0, 240, 20))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        
    def new_session(self):
        self.timeEdit.setSpecialValueText("00:00:00")
        self.pushButton_3.setEnabled(True)
        self.pushButton.setEnabled(True)
        self.pushButton_4.setEnabled(True)
        self.new_session_button.setEnabled(False)
        self.repaint()